num-server-rounds = 100
algorithm = "fedamp"

fraction-fit = 0.4
fraction-evaluate = 1.0

partition-by = 'label'
num-classes-per-partition = 3

local-epochs = 4
learning-rate = 0.01
batch-size = 32

num-clients = 40

alpha = 0.1
sigma = 1.0
fedamp_lambda = 1.0

save-dir = "fedamp_results/"